language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4fdias
  api_key:
    secure: k+kWLrNT2kgLoceoC49AwTyZlOdwyAxpIFgjx4ygJs0uobZvqC/WhvI5V13QdcGjMI+GgOl5xKLE/yT/fS5C2LnIPTle7Rlz3dyUazyej1RHl70O2Zc1awY/cnyjXb7FWbGMruOSf9sRVJQCSvxiwtsELUq8rJXDw4JE6sZPHkAHUa0B7Wn1DdiSL2disRINq+QeLl7TYm6l/zj1QjA7Y90xTClCz28wDvIa1YNyq7t/ReWVMWM82zDN+cgE59SR0Gmh7jt5QH3Oqo2zeFNjeDLKyFmxnDk0dNqw5MsUWKmF84u2Q+v1uC9PiEDSsS/kJ9UDRqZ+dnobTLUJraLQNRyE5APypCSb2qMxmxZ/0KZnjW5uCdEx/ISopXnKAj1yu2uG04SoFNX9Ldr17+HIMXUafoT6wASnKm9fWpqv2xtpT9xI8pOzfqiAwShElJaStVVoUtsbrMFn2rPGeQlwozQsWB/7W/Qfr+503fRleCLz5YJJBeIxUz/LFVGhMNe/YoLXChvTWhekD/mXw6hJMvqKkJQdH+bB4fi9nyAVmh/CGC3rLIqjLFRo6SibeKMDKOBem+0/IGidqxb0YyBJpKtiZi1tf9lCc3LEuWNWpGThaKP21ef/23pKefsjtYGmZDunO3dbq5hwAI01vLFLUSMS2550TVH8bkppbwZRVYM=
